package.json, src/components/Account.jsx, src/components/Transactions.jsx, vercel.deployment.sh
=> chore: update query transactions of deposit address

package-lock.json, package.json, src/components/EVMPoll.jsx, src/components/GMP.jsx, src/components/GMPs.jsx, src/components/Header.jsx, src/components/Logo.jsx, src/components/Search.jsx, src/components/Transactions.jsx, src/components/Transfer.jsx, src/components/Transfers.jsx
=> chore: display search bar on nav bar for mobile view

src/app/layout.jsx, src/components/Header.jsx, src/components/Layout.jsx, tailwind.config.js
https://github.com/axelarnetwork/axelarscan-ui/issues/36
styling header on TVL page
=> feat: styling header on TVL page

src/components/Transaction.jsx
https://github.com/axelarnetwork/axelarscan-ui/issues/38
=> fix: parsing raw_log of error tx

package.json, src/components/GMP.jsx, src/lib/number.js
https://github.com/axelarnetwork/axelarscan-ui/issues/40
=> feat: update path display for multihop

package-lock.json, package.json, src/components/GMP.jsx, src/components/GMPs.jsx
https://github.com/axelarnetwork/axelarscan-ui/issues/31
=> feat: custom recipient for interchain transfer

src/components/Validators.jsx
https://github.com/axelarnetwork/axelarscan-ui/issues/32
=> feat: merge EVM votes and supported columns, allow sorting by columns

src/components/Interchain.jsx
https://github.com/axelarnetwork/axelarscan-ui/issues/33
=> feat: custom nodeTooltip for sankey chart

src/components/TVL.jsx
https://github.com/axelarnetwork/axelarscan-ui/issues/33
- default including ITS
- chore: styling font size & line height for Total & Moved columns
=> feat: default including ITS & styling

src/data/accounts/index.js
https://github.com/CoinHippo-Labs/axelarscan-ui/pull/277
=> chore: adding Stake DAO Ethereum State Sender

src/lib/api/name-services/ens.js
https://github.com/axelarnetwork/axelarscan-ui/issues/70
=> chore: update ens subgraph url

src/components/GMPs.jsx, src/components/Transfers.jsx
https://github.com/axelarnetwork/axelarscan-ui/issues/75
=> feat: add received/executed link to status on GMPs/Transfers page

.env
per this [discussion](https://interoplabs.slack.com/archives/C035KBHNP8A/p1721697502761969)
=> feat: Update banner message

src/components/Footer.jsx
https://interoplabs.slack.com/archives/C035KBHNP8A/p1723034270022999
=> feat:update X URL

src/components/Overview.jsx
https://interoplabs.slack.com/archives/C035KBHNP8A/p1724113752304539
=> feat: update evm rate to 0.2%

.env
https://interoplabs.slack.com/archives/C035KBHNP8A/p1729524743426269
=> chore: update banner message

package-lock.json, package.json, src/app/providers.jsx, src/components/GMP.jsx, src/components/Wallet.jsx
This PR integrates the Add Gas for SUI functionality to the GMP page of Axelarscan UI. 
**Jira ticket:** https://axelarnetwork.atlassian.net/browse/AXE-6546
https://github.com/axelarnetwork/axelarjs-sdk/pull/335
=> feat: addGasToSuiChain

src/components/GMP.jsx, src/lib/api/name-services/lens.js, src/lib/api/name-services/unstoppable.js, src/lib/chain/index.js
- hide step approved when executed or error occur
- disable unstoppable & lens
=> feat: add executeButton for cosmos -> cosmos

package-lock.json, package.json, src/components/Global.jsx, src/components/Interchain.jsx
Jira ticket: https://axelarnetwork.atlassian.net/browse/AXE-8103
=> chore: remove Active Users chart when filtering squid coral

src/components/GMP.jsx
https://interoplabs.slack.com/archives/C085AKTCK35/p1742491187320859
=> chore: (non-evm) remove error (reverted) link

package.json
Jira: https://axelarnetwork.atlassian.net/browse/AXE-8309
=> chore: update next 14.2.26

package.json, src/components/GMP.jsx
update SDK version to `0.17.5-alpha.3` to address the issue reported in https://interoplabs.slack.com/archives/C05AQS22GER/p1749757150040049
=> chore: update sdk version

src/data/accounts/index.js
Adding Centrifuge V3 to Axelar scan for address `0x52271c9a29d0f97c350bbe32b3377cdd26026d0a`
=> Update index.js to include Centrifuge
